include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Enabled.
    directives_ordering: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    # Disabled.
    constant_identifier_names: false
